[workspace]
authors = ["larry <xspanni@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "advisor"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
openai = ">=2.8.0,<3"
